version: "3.7"
services:
    app:
        build:
            args:
                user: php-user
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: crdtenant
        container_name: crdtenant-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - crdtenant

    db:
        image: mysql
        container_name: crdtenant-db
        restart: "unless-stopped"
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: crud_app_vue
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - crdtenant

    nginx:
        image: nginx:alpine
        container_name: crdtenant-nginx
        restart: unless-stopped
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - crdtenant

volumes:
    dbdata:
        driver: local

networks:
    crdtenant:
        driver: bridge
